---
- name: "Install dependencies"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - g++
    - git

- name: "Clone it"
  git:
    repo: 'https://github.com/AGWA/git-crypt.git'
    dest: "{{ repo_location }}"

- name: "Set default ownership"
  file:
    state: directory
    recurse: true
    path: "{{ repos_location }}"
    owner: "{{ real_user }}"
    group: "{{ real_user_group }}"

- name: "Compile it"
  make:
    chdir: "{{ repo_location }}"

- name: "Install it"
  make:
    chdir: "{{ repo_location }}"
    target: install
