---
- name: "Adding Virtualbox' key"
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox.asc"

- name: "Adding Virtualbox' repository"
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"
    update_cache: yes

- name: "Installing Virtualbox"
  apt:
    name: virtualbox-5.1
    allow_unauthenticated: yes
    state: latest

- name: "Installing Virtualbox-dkms"
  apt:
    name: dkms
    state: latest
