---
- name: "Adding key"
  apt_key:
    keyserver: pgp.mit.edu
    id: 5044912E

# These are all the repositories that dropbox have:
# https://linux.dropbox.com/ubuntu/dists/
- name: "Adding repository"
  apt_repository:
    repo: "deb http://linux.dropbox.com/ubuntu xenial main"

- name: "Installing package"
  apt:
    name: "dropbox"
    state: latest
