---
- name: "Downloading docker installation script"
  get_url:
    url: https://get.docker.com/
    dest: /tmp/install_docker.sh
    mode: 0755

- name: "Installing Docker"
  shell: "/bin/sh /tmp/install_docker.sh"

- name: "Adding current user to docker group"
  user:
    name: "{{ real_user }}"
    groups: docker
    append: yes

- name: "Installing docker-compose"
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items:
    - pyopenssl
    - docker-compose
