---
- name: "Installing dependencies"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - curl

- name: "Installing Docker"
  shell: "curl -sSL https://get.docker.com/ | sh"

- name: "Adding current user to docker group"
  user:
    name: "{{ real_user }}"
    groups: docker
    append: yes

- name: "Installing docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
