---
- name: "Installing vim"
  apt: name=vim-gtk state=latest

- name: "Installing the Silver Searcher"
  apt:
    name: silversearcher-ag
    state: latest

- name: "Creating .vim directory"
  file:
    dest: "{{ real_user_home }}/.vim/bundle"
    state: directory
    group: "{{ real_user_group }}"
    owner: "{{ real_user }}"

- name: "Getting neoBundle"
  git:
    repo: "https://github.com/Shougo/neobundle.vim"
    dest: "~/.vim/bundle/neobundle.vim"

- name: "Copying vimrc file"
  copy:
    src: vimrc
    dest: "{{ real_user_home }}/.vim/vimrc"
    owner: "{{ real_user }}"
    group: "{{ real_user_group }}"
