- name: "Add neovim PPA"
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    codename: 'xenial'

- name: "Install neovim"
  apt:
    name: neovim
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: "Install neovim python module"
  pip:
    name: neovim
    extra_args: --upgrade

- name: "Prepare destination directory"
  file:
    state: directory
    path: "{{ real_user_home }}/.local/share/nvim/site/autoload/"
    owner: "{{ real_user }}"
    group: "{{ real_user_group }}"

- name: "Install Plug"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ real_user_home }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0755
    owner: "{{ real_user }}"
    group: "{{ real_user_group }}"

- name: "Use neovim for everything"
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/nvim
  with_items:
    - vi
    - vim
    - editor
